CREATE TABLE faces (
    episode_id              INT NOT NULL,
    frame_num               INT NOT NULL,
    face_num                INT NOT NULL,
    series_id               INT NOT NULL,
    filename                VARCHAR(512),
    x1                      INT NOT NULL,
    y1                      INT NOT NULL,
    x2                      INT NOT NULL,
    y2                      INT NOT NULL,
    right_eye_x             INT,
    right_eye_y             INT,
    left_eye_x              INT,
    left_eye_y              INT,
    nose_x                  INT,
    nose_y                  INT,
    mouth_right_x           INT,
    mouth_right_y           INT,
    mouth_left_x            INT,
    mouth_left_y            INT,
    confidence              FLOAT,
    img_height              INT,
    img_width               INT,
    pct_of_frame            FLOAT,
    distance_from_center    FLOAT,
    cast_id                 INT,
    PRIMARY KEY (episode_id, frame_num, face_num)
)