CREATE TABLE series (
    series_id                       INT NOT NULL PRIMARY KEY,
    title                           VARCHAR(255),
    localized_title                 VARCHAR(255),
    original_title                  VARCHAR(255),
    year                            INT,
    series_years                    VARCHAR(255),
    num_seasons                     INT,
    num_episodes                    INT,
    genres                          VARCHAR(255),
    countries                       VARCHAR(255),
    country_codes                   VARCHAR(255),
    language_codes                  VARCHAR(255),
    color_info                      VARCHAR(255),
    aspect_ratio                    VARCHAR(255),
    rating                          FLOAT,
    votes                           INT,
    avg_face_pct_of_frame           FLOAT,
    avg_faces_per_frame             FLOAT,
    avg_face_distance_from_center   FLOAT
);